'''
  Author: DawsonLin
  Email: lin_dongsen@126.com
  Created: 2025-10-18
  Purpose: Utility functions for data formatting and conversion
'''

import re
import simplejson
from collections import OrderedDict

from .json_tool import safe_json_dump


TOPSAILAI_FORMAT_PREFIX = "topsailai."


def to_list(v, to_ignore_none=False):
    """Convert a value to a list, handling various input types.

    This function converts different data types to a list format. It handles
    lists, sets, tuples, None values, and single values appropriately.

    Args:
        v: Value to convert to list
        to_ignore_none: If True and v is None, returns None instead of [None]

    Returns:
        list or None: Converted list, or None if to_ignore_none is True and v is None

    Examples:
        to_list([1, 2, 3]) -> [1, 2, 3]
        to_list((1, 2, 3)) -> [1, 2, 3]
        to_list({1, 2, 3}) -> [1, 2, 3]
        to_list(42) -> [42]
        to_list(None) -> [None]
        to_list(None, to_ignore_none=True) -> None
    """
    if isinstance(v, (list, set, tuple)):
        return list(v)
    if v is None:
        if to_ignore_none:
            return v
    return [v]

def fix_llm_mistakes(text:str, step_keys=("thought", "action")):
    """Fix common formatting mistakes in LLM-generated text.

    This function corrects formatting issues in text generated by language models,
    specifically addressing problems with topsailai format step markers.

    Args:
        text: Input text that may contain formatting errors
        step_keys: Tuple of step names to check for formatting issues

    Returns:
        str: Text with corrected formatting

    Fixes applied:
    - Missing newline before step markers: "topsailai.action" -> "\ntopsailai.action"
    - Missing newline after step markers: "topsailai.actionxxx" -> "topsailai.action\nxxx"
    """
    for step_key in step_keys:
        step_name = TOPSAILAI_FORMAT_PREFIX + step_key

        if f"\n{step_name}\n" in text:
            continue

        # case: xxx{step_name}\n
        if f"{step_name}\n" in text:
            text = text.replace(step_name, f"\n{step_name}", 1)
            continue

        # case: \n{step_name}xxx
        if f"\n{step_name}" in text:
            text = text.replace(step_name, f"{step_name}\n", 1)
            continue

    return text

def parse_topsailai_format(text: str) -> dict:
    """
    Parse text in the topsailai format.

    Format:
    topsailai.{step_name}
    {raw_text}

    Returns a dictionary where keys are step names and values are raw text content.
    """
    text = fix_llm_mistakes(text)
    lines = text.strip().split('\n')
    if not lines:
        return {}

    result = OrderedDict()
    current_step = None
    current_content = []

    for line in lines:
        # Check if line starts a new step
        if line.startswith(TOPSAILAI_FORMAT_PREFIX):
            # Save previous step if exists
            if current_step:
                result[current_step] = '\n'.join(current_content).strip()

            # Start new step
            step_name = line[len(TOPSAILAI_FORMAT_PREFIX):].strip()
            current_step = step_name
            current_content = []
        elif current_step:
            # Add to current step's content
            current_content.append(line)

    # Don't forget the last step
    if current_step:
        result[current_step] = '\n'.join(current_content).strip()

    return result

def parse_topsailai_format_regex(text: str) -> dict:
    """Parse text in the topsailai format using regular expressions.

    This function uses regex pattern matching to extract step names and content
    from topsailai formatted text. It returns an ordered dictionary with step names
    as keys and their corresponding content as values.

    Args:
        text (str): Input text in topsailai format.

    Returns:
        dict: Ordered dictionary where keys are step names and values are content.
    """
    pattern = r'topsailai\.(\w+)\n(.*?)(?=\ntopsailai\.|\Z)'
    matches = re.findall(pattern, text, re.DOTALL)

    result = OrderedDict()
    for step_name, content in matches:
        result[step_name] = content.strip()

    return result

def format_dict_to_list(d:dict, key_name:str, value_name:str) -> list[dict]:
    """Convert a dictionary to a list of dictionaries with specified key-value structure.

    This function transforms a dictionary into a list where each element is a dictionary
    containing the original key and value under specified field names.

    Args:
        d: Input dictionary to convert
        key_name: Field name to use for dictionary keys
        value_name: Field name to use for dictionary values

    Returns:
        list[dict]: List of dictionaries with the specified structure

    Example:
        >>> format_dict_to_list({"a": 1, "b": 2}, "name", "value")
        [{"name": "a", "value": 1}, {"name": "b", "value": 2}]
    """
    if not d:
        return []

    result = []
    for k, v in d.items():
        result.append(
            {
                key_name: k,
                value_name: v,
            }
        )
    return result

def to_topsailai_format(content:str|list|dict, key_name:str, value_name:str, for_print=False) -> str:
    """Convert content to topsailai format string.

    This function converts various data types to the topsailai format, which is
    a structured text format used for representing agent steps and actions.

    Args:
        content: Input content (string, list, or dictionary)
        key_name: Field name to use as step identifier
        value_name: Field name to use as step content
        for_print: If True, format complex values for better readability

    Returns:
        str: Formatted string in topsailai format

    Format:
        topsailai.{key_name}
        {value_content}
        {remaining_fields_as_json}

    Example:
        >>> to_topsailai_format([{"step": "think", "text": "I need to..."}], "step", "text")
        "topsailai.think\nI need to...\n\n"
    """
    if isinstance(content, str):
        if key_name not in content:
            return content
        content = simplejson.loads(content)

    result = ""
    for d in to_list(content):
        # d is dict
        # keywords:
        #   step_name
        #   raw_text
        #   tool_call ...
        result += f"{TOPSAILAI_FORMAT_PREFIX}{d[key_name]}\n"
        del d[key_name]
        if value_name in d:
            v = d[value_name]
            if for_print:
                if isinstance(v, (list, dict)):
                    v = safe_json_dump(v)
            result += f"{v}\n"
            del d[value_name]
        if d:
            result += safe_json_dump(d) + "\n"
        result += "\n"
    return result
