[project]
name = "rag-traditional"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.2.1",
    "sentence-transformers>=5.1.1",
    "sentencepiece>=0.2.1",
]
