"""
Constants module for AI Agent framework.

This module defines common constants used throughout the AI Agent framework,
primarily role definitions for message handling in conversational AI systems.
"""

# Role definitions for message types in conversational AI systems
# These roles are used to categorize messages in the conversation history
ROLE_USER = "user"        # Messages from the human user
ROLE_ASSISTANT = "assistant"  # Messages generated by the AI assistant
ROLE_SYSTEM = "system"    # System-level messages and prompts
ROLE_TOOL = "tool"        # Messages containing tool execution results